sudo : required
language: node_js
node_js:
  - 7
services :
  - docker

before_install:
  - docker build -f Dockerfile.dev -t ujjwal25/docker-react . 


script:
  -docker run ujjwal25/docker-react npm run test -- --coverage